language: generic

cache:
    directories:
    - $HOME/.dotnet-sdk-osx
    - $HOME/.ChakraCore
    - $HOME/.nuget/packages

addons:
  apt:
    packages:
    - build-essential
    - gettext
    - clang-3.8
    - cmake
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - libunwind8-dev
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      runtime:
        - name: netcore
          version: 2
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.0
    - os: osx
      osx_image: xcode9.1
      runtime:
        - name: netcore
          version: 2
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.0

before_install:
  - mkdir -p /usr/local/lib
  - export DOTNET_SDK_OSX=.dotnet-sdk-osx
  - export CHAKRACORE_PATH=.ChakraCore
  - export CHAKRALIBS="$HOME/$CHAKRACORE_PATH/libs/"
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      sw_vers -productVersion;
      if [ ! -d "$DOTNET_SDK_OSX" ]; then
        mkdir -p "$DOTNET_SDK_OSX";
        export DOTNET_SDK_URL="https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-osx-x64.pkg";
        curl -L "$DOTNET_SDK_URL" -o "$DOTNET_SDK_OSX/dotnet-sdk-2.0.0-osx-x64.pkg";
      fi;
      sudo installer -pkg "$DOTNET_SDK_OSX/dotnet-sdk-2.0.0-osx-x64.pkg" -target "/";
      eval $(/usr/libexec/path_helper -s);
      if [ ! -d "$CHAKRALIBS" ]; then
        curl -L https://aka.ms/chakracore/cc_osx_x64_1_7_3 -o chakracore;
        tar -xvzf chakracore;
        mkdir -p $CHAKRALIBS;
        cp ./ChakraCoreFiles/lib/libChakraCore.dylib $CHAKRALIBS;
      fi;
    else
      lsb_release -a;
      which $cc;
      sudo apt-get install curl;
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg;
      sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg;
      sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
      sudo apt-get update;
      sudo apt-get install -y dotnet-sdk-2.0.0;
      if [ ! -d "$CHAKRALIBS" ]; then
        curl -L "https://aka.ms/chakracore/cc_linux_x64_1_7_3" -o chakracore;
        tar -xvzf chakracore;
        mkdir -p "$CHAKRALIBS";
        cp "./ChakraCoreFiles/lib/libChakraCore.so" "$CHAKRALIBS";
      fi;
    fi;

install:
  # Copy pre-compiled libraries to ChakraCore
  - cp -rf $CHAKRALIBS/. ./lib/ChakraCore/
  # Ensure chakra libraries are updated by listing them
  - ls -l ./lib/ChakraCore/
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found";
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore -v Minimal

script:
  # Run tests
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK ./test/BaristaLabs.BaristaCore.Tests/
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK ./test/BaristaLabs.BaristaCore.Extensions.Tests/ -v d