language: generic

addons:
  apt:
    packages:
    - gettext
    - clang-3.8
    - cmake
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0
    - os: osx
      osx_image: xcode8.1
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      sw_vers -productVersion;
      export DOTNET_INSTALL_DIR="$PWD/.dotnetcli";
      mkdir $DOTNET_INSTALL_DIR;
      brew install openssl;
      mkdir -p /usr/local/lib;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=834982";
      curl -L $DOTNET_SDK_URL -o dotnet_package;
      tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR;
      export PATH="$DOTNET_INSTALL_DIR:$PATH";
    else
      lsb_release -a;
      which $cc;
      sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
      sudo apt-get update;
      sudo apt-get install -y build-essential cmake clang-3.8 libicu-dev dotnet-dev-1.0.0-preview2.1-003177;
    fi

install:
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found";
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore

script:
  # Run tests
  - ls ./test/BaristaLabs.BaristaCore.Tests/bin/Release/netcoreapp1.0/ChakraCore/
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK ./test/BaristaLabs.BaristaCore.Tests/