language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0.1
    - os: osx
      osx_image: xcode8.1
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0.1

before_install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - mkdir $DOTNET_INSTALL_DIR
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      brew install openssl;
      brew link --force openssl;
      mkdir -p /usr/local/lib;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=827533";
      curl -L $DOTNET_SDK_URL -o dotnet_package;
      tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR;
    else
      sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177;
    fi

  # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found";
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore

script:
  # Run tests
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK Source/NSubstitute.Acceptance.Specs