language: generic

cache:
    directories:
    - $HOME/.ChakraCore
    - $HOME/.nuget/packages

addons:
  apt:
    packages:
    - build-essential
    - gettext
    - clang-3.8
    - cmake
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - libunwind8-dev
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0
    - os: osx
      osx_image: xcode8.1
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.0

before_install:
  - mkdir -p /usr/local/lib
  - export CHAKRACORE_PATH=.ChakraCore
  - export CHAKRALIBS="$HOME/$CHAKRACORE_PATH/libs/"
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      sw_vers -productVersion;
      export DOTNET_INSTALL_DIR="$PWD/.dotnetcli";
      mkdir $DOTNET_INSTALL_DIR;
      brew install icu4c openssl;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=834982";
      curl -L $DOTNET_SDK_URL -o dotnet_package;
      tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR;
      export PATH="$DOTNET_INSTALL_DIR:$PATH";
      if [ ! -d "$CHAKRALIBS" ]; then
        xcode-select --install;
        brew install cmake;
        git clone https://github.com/Microsoft/ChakraCore;
        cd ChakraCore;
        git fetch origin pull/2056/head:debug;
        git checkout debug;
        ./build.sh --icu=/usr/local/opt/icu4c/include;
        cd ..;
        mkdir -p $CHAKRALIBS;
        cp ./ChakraCore/BuildLinux/Release/bin/ChakraCore/libChakraCore.dylib $CHAKRALIBS;
      fi
    else
      lsb_release -a;
      which $cc;
      sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
      sudo apt-get update;
      sudo apt-get install -y build-essential clang-3.8 libunwind8 libunwind8-dev libicu-dev dotnet-dev-1.0.0-preview2.1-003177;
      if [ ! -d "$CHAKRALIBS" ]; then
        export CMAKE_INSTALL_DIR="$PWD/.cmake";
        mkdir $CMAKE_INSTALL_DIR;
        wget https://cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz;
        tar --strip-components=1 -xvzf ./cmake-3.7.0-Linux-x86_64.tar.gz -C $CMAKE_INSTALL_DIR;
        export PATH="$CMAKE_INSTALL_DIR/bin:$PATH";
        cmake --version;
        git clone https://github.com/Microsoft/ChakraCore;
        cd ChakraCore;
        git fetch origin pull/2056/head:debug;
        git checkout debug;
        ./build.sh --cxx=/usr/bin/clang++-3.8 --cc=/usr/bin/clang-3.8;
        cd ..;
        mkdir -p $CHAKRALIBS;
        cp ./ChakraCore/BuildLinux/Release/bin/ChakraCore/libChakraCore.so $CHAKRALIBS;
     fi
    fi

install:
  # Copy pre-compiled libraries to ChakraCore
  - cp -rf $CHAKRALIBS/. ./lib/ChakraCore/
  # Ensure chakra libraries are updated by listing them
  - ls -l ./lib/ChakraCore/
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found";
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore -v Minimal

script:
  # Run tests
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK ./test/BaristaLabs.BaristaCore.Tests/