version: 1.0.{build}
configuration:
  - Release
platform: x64
environment:
  FRAMEWORK: netcoreapp1.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  - cmd: appveyor-retry dotnet restore -v Minimal
build_script:
  - cmd: dotnet build -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\
test_script:
  - cmd: dotnet test -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\
cache:
  - '%USERPROFILE%\.nuget\packages'