version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
platform: x64
environment:
  FRAMEWORK: netcoreapp2.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN: 7c1iHfH8bvABxL9ePXzvukfeVYM2txph8
  DOTNET_INSTALL_DIR: C:\Program Files\dotnet
init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
before_build:
  - cmd: set
  - cmd: dotnet --info
  - cmd: appveyor-retry dotnet restore -v Minimal
build_script:
  - cmd: dotnet build -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\
test_script:
  - cmd: dotnet test -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\
after_test:
  # Use vstest to gather code coverage and submit to coveralls via coveralls.net (test project dependency)
  # - ps: $vstest = "VSTest.Console.exe"
  # - ps: '& $vstest "$env:APPVEYOR_BUILD_FOLDER\test\BaristaLabs.BaristaCore.Tests\BaristaLabs.BaristaCore.Tests.csproj" /enablecodecoverage'
  # - ps: $coveralls = "$env:HOMEPATH\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.coveralls.exe"
  # - ps: '& $coveralls --opencover -i opencoverCoverage.xml --useRelativePaths --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID'
cache:
  - '%USERPROFILE%\.nuget\packages'