version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
platform: Any CPU
environment:
  FRAMEWORK: netcoreapp2.1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN: 7c1iHfH8bvABxL9ePXzvukfeVYM2txph8
  DOTNET_INSTALL_DIR: C:\Program Files\dotnet
init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
before_build:
  - cmd: set
  - cmd: dotnet --info
build_script:
  build: off
  # - cmd: dotnet build -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\
  # - cmd: dotnet build -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Extensions.Tests\
test_script:
  - cmd: dotnet test -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Tests\ /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\"
  - cmd: dotnet test -c %CONFIGURATION% -f %FRAMEWORK% test\BaristaLabs.BaristaCore.Extensions.Tests\ /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\"
after_test:
  - cmd: dotnet tool install -g coveralls.net --version 1.0.0
  - cmd: csmacnz.Coveralls --opencover -i ./test/BaristaLabs.BaristaCore.Tests/coverage.opencover.xml --useRelativePaths --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID'
cache:
  - '%USERPROFILE%\.nuget\packages'