//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaristaLabs.BaristaCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaristaLabs.BaristaCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**!
        ///
        /// @license
        /// handlebars v4.0.11
        ///
        ///Copyright (C) 2011-2017 by Yehuda Katz
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string handlebars_min {
            get {
                return ResourceManager.GetString("handlebars_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** @license React v16.2.0
        /// * react.production.min.js
        /// *
        /// * Copyright (c) 2013-present, Facebook, Inc.
        /// *
        /// * This source code is licensed under the MIT license found in the
        /// * LICENSE file in the root directory of this source tree.
        /// */
        ///&apos;use strict&apos;;(function(q,k){&quot;object&quot;===typeof exports&amp;&amp;&quot;undefined&quot;!==typeof module?module.exports=k():&quot;function&quot;===typeof define&amp;&amp;define.amd?define(k):q.React=k()})(this,function(){function q(a){for(var b=arguments.length-1,c=&quot;Minified React error #&quot;+a+&quot;; visit http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string react_production_min {
            get {
                return ResourceManager.GetString("react_production_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;use strict&quot;;var __assign=this&amp;&amp;this.__assign||Object.assign||function(e){for(var t,n=1,r=arguments.length;n&lt;r;n++){t=arguments[n];for(var i in t)Object.prototype.hasOwnProperty.call(t,i)&amp;&amp;(e[i]=t[i])}return e},__extends=this&amp;&amp;this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&amp;&amp;function(e,t){e.__proto__=t}||function(e,t){for(var n in t)t.hasOwnProperty(n)&amp;&amp;(e[n]=t[n])};return function(t,n){function r(){this.constructor=t}e(t,n),t.prototype=null===n?Object.create(n):(r.pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string typescript_min {
            get {
                return ResourceManager.GetString("typescript_min", resourceCulture);
            }
        }
    }
}
